---
title: "Determinants of Foreign Aid from the United States"
author: "Kenneth Catlin & Peyton Keleher"
date: "2023-03-29"
output: html_document
---

```{r Loading data - libraries - cleaning data, echo=FALSE}
#Load libraries & Import Data
library("dplyr")
library("tidyr")
#set constraints to zero

forass<-read.csv("https://raw.githubusercontent.com/Chromaticluv/Stat461project/main/foreignassistance.csv") #Foreign Assistence data set
politydata<-read.csv("https://raw.githubusercontent.com/Chromaticluv/Stat461project/main/polity.csv") #POLITY V DATA SET
worldbankraw<-read.csv("https://raw.githubusercontent.com/Chromaticluv/Stat461project/main/WorldBankData.csv")

#NOTE: the original Foreign Assistance data set was over 3gb in size. For convenience, it was cleaned in a seperate file, then the final
#set was saved and imported here. A full data set can be found at: https://data.usaid.gov/resource/azij-hu6e.json

##Cleaning polity data:
politydata<-read.csv("https://raw.githubusercontent.com/Chromaticluv/Stat461project/main/polity.csv")
politydata<-politydata %>% 
  rename(byear = Fiscal.Year) %>%
  select(Country.Code,country,polity,byear,eyear) %>% #select only relevant rows
  filter(between(eyear,2000,9999)) #select only rows between end-year 2000 and present.

politydata$eyear[politydata$eyear == 9999] <- 2020 #turn "present" values to 2020
politydata$polity[politydata$polity < -10] <- NA #turn transition years into NA

##clean worldbank

worldbankclean<-worldbankraw %>%
  filter(Series.Code =="NY.GDP.PCAP.CD") #only select rows for GDP per capita
  
worldbankclean<-gather(worldbankclean, Year, GDP_per_cap, X2000..YR2000.:X2015..YR2015.) #Convert wide data to long

worldbankfinal<-worldbankclean %>%
  select(Country.Code,Country.Name,Year,GDP_per_cap) #select relevant columns

worldbankfinal$GDP_per_cap[worldbankfinal$GDP_per_cap == ".."] <- NA #change ".." to NA

#Recoding all the weird year formats to something normal. (and numeric)
worldbankfinal$Year[worldbankfinal$Year =="X2000..YR2000."] <- 2000
worldbankfinal$Year[worldbankfinal$Year =="X2001..YR2001."] <- 2001
worldbankfinal$Year[worldbankfinal$Year =="X2002..YR2002."] <- 2002
worldbankfinal$Year[worldbankfinal$Year =="X2003..YR2003."] <- 2003
worldbankfinal$Year[worldbankfinal$Year =="X2004..YR2004."] <- 2004
worldbankfinal$Year[worldbankfinal$Year =="X2005..YR2005."] <- 2005
worldbankfinal$Year[worldbankfinal$Year =="X2006..YR2006."] <- 2006
worldbankfinal$Year[worldbankfinal$Year =="X2007..YR2007."] <- 2007
worldbankfinal$Year[worldbankfinal$Year =="X2008..YR2008."] <- 2008
worldbankfinal$Year[worldbankfinal$Year =="X2009..YR2009."] <- 2009
worldbankfinal$Year[worldbankfinal$Year =="X2010..YR2010."] <- 2010
worldbankfinal$Year[worldbankfinal$Year =="X2011..YR2011."] <- 2011
worldbankfinal$Year[worldbankfinal$Year =="X2012..YR2012."] <- 2012
worldbankfinal$Year[worldbankfinal$Year =="X2013..YR2013."] <- 2013
worldbankfinal$Year[worldbankfinal$Year =="X2014..YR2014."] <- 2014
worldbankfinal$Year[worldbankfinal$Year =="X2015..YR2015."] <- 2015

#merge forass and worldbank on country code and year.

forass<-forass %>%
  rename(Year = Fiscal.Year)

merged1<-merge(x=forass, y=worldbankfinal, by = c("Country.Code","Year"), all = FALSE)

merged2<-merged1 %>%
  select(Country.Code,Country.Name.x,Country.Name.y,Current.Dollar.Amount,Year,GDP_per_cap)

min(merged2$Year)
max(merged2$Year)
countries<-unique(merged2$Country.Name.x)
unique(merged2$year)
summary(countries)

#create a new data frame wher #current_dollar_value is summated into a single value
#each row will be a single country, with a single year, and a unique dollar value.
#then, create a column for "Polity" score, to be populated by reference to the polity dataset.

#use politydata as a relational table to fill in polity values in merged data set

#create a new data.frame
merged3<-data.frame(
  "Country" = c(countries),
  "Country Code" = c(countrycodes),
  "Year" = c(years),
  "Tot_spend" = () #total military spending. this one is probably going to require a loop.
  "Polity" = 
)

#loop for populationg polity scores
merged3$polity<-
  for x in merged3
  polity == politydata$polity
  where
  merged3$country == politydata$Country.Code
  AND
  politydata$byear > merged3$year >= politydata$eyear
  
  OR
  
  for x in merged3
  if polity$country[i] == merged3$country[j]
  AND polity$byear[j] > merged3$year > polity$eyear[j]
  THEN merged3$polity = politydata$polity
  ELSE
  



#Select sample size. 
#to produce a balanced design, create a "regime type) variable denoting each country
#as either dem or non-dem (1,0), based of Polity2 score. (dem => 7)
#Then, divide the sample size by two, and select that many countries from each category
#using the "seed" function.

set.seed(12)
countriessample<-sample(countries,66)
View(countriessample)
print(countriessample)
#merge Polity, formal aliances, and Wealth into this data set as well (will need done before step above)
```

###Introduction

###Literature Review

###Assessing the data

```{r Summary data, distributions, assumptions, echo=FALSE}

plot(merged2$GDP_per_cap, merged2$Current.Dollar.Amount)
#produce summary statistics for DV

#produce a histogram of the DV (data$current_amount)

###assess ANOVA assumpetions
#Gaussian distribution via QQ plot

#Homoscedacity via strip plot

#Independence via D-W statistic

#spherecity 

```

###METHODOLY

```{r, echo=FALSE}
##Hasse Diagram

#conduct ANOVA test(s)

``` 

###POST HOC ANALYSIS

```{r, echo=FALSE}

```

###RESULTS

###CONCLUSION

###REFERENCES 

###APENDIX